---
title: "R para Dummies en Fitopatología"
---

# Descubriendo el mundo del análisis de datos en R

#### ¡Descubre el Poder de R y Quarto!

¿Te imaginas dominar un lenguaje de programación que no solo te permita realizar análisis de datos avanzados, sino que también te proporcione una plataforma interactiva para documentar y compartir tus hallazgos de manera profesional? ¡Es posible con R y Quarto! R es un entorno de software estadístico increíblemente versátil que, junto con Quarto, una interfaz amigable y dinámica, hace que el análisis estadístico sea accesible y eficiente para todos. Imagina poder crear informes claros, visualizaciones detalladas y modelos complejos con una sintaxis intuitiva y una comunidad de apoyo inigualable. No solo estarás aprendiendo una habilidad valiosa, sino que te estarás alineando con las tendencias tecnológicas emergentes, preparando tus análisis para el futuro.

Al entrar en el fascinante mundo del análisis de datos con RStudio, es importante saber por dónde empezar. Existen muchos materiales interesantes y extremadamente útiles disponibles, solo necesitas acceder a ellos y saber cómo usar la información a tu favor. Entre los materiales disponibles, libros como [Introducción a la Ciencia de Datos en R](https://r4ds.hadley.nz/), [Introduction to R](https://intro2r.com/), y [The Art of Data Science](https://bookdown.org/rdpeng/artofdatascience/) son esenciales para obtener una comprensión básica de la ciencia de datos y un entendimiento más profundo de cómo realizar exploración y análisis de datos correctamente en R.

Es importante resaltar que los materiales presentados en este sitio son clases que fueron creadas con el objetivo de agregar conocimiento. Sin embargo, debido a la complejidad de los temas, no fue posible realizar anotaciones detalladas sobre todos los asuntos abordados, por lo tanto, este no debe ser tu punto de partida para el estudio de análisis. Estos materiales, por sí solos, no son capaces de elucidar cuestiones complejas del R, por eso es importante no enfocarse únicamente en este contenido. Así, comenzamos nuestra jornada de conocimiento en R presentando algunos de sus objetos y funciones más básicos.

## **Instalación de R y RStudio**

Para empezar a trabajar con R, necesitarás instalar R y RStudio:

1.  Descarga e instala [R](https://cran.r-project.org/).
2.  Descarga e instala [RStudio](https://www.rstudio.com/products/rstudio/download/).

## Objetos y funciones

**Objeto**: Un objeto es simplemente un nombre que guarda un valor y, para crearlo, utilizamos el operador `<-`. Ej.: `a <- 1`. En R, una base de datos es representada por objetos llamados data frames. Siempre que se ejecuta una función, el código que guarda será ejecutado y un resultado nos será devuelto. Entre paréntesis, después del nombre de la función, tenemos lo que llamamos *argumentos*. Una función puede tener cualquier número de argumentos y ellos siempre están separados por comas. Ej.: `sum(1, 2)`. La función `sum()` recibió los argumentos `1` y `2`.

**Clases**: Para crear texto en R, colocamos los caracteres entre comillas (" "). Las comillas sirven para diferenciar nombres (objetos, funciones, paquetes) de textos (letras y palabras). Los textos son muy comunes en variables categóricas. Las clases más básicas dentro de R son: `numeric`, `character` y `logical`.

**Vectores**: Los vectores en R son solo conjuntos indexados de valores. Para crearlos, solo necesitas poner los valores separados por comas dentro de un `c()`. Cada columna de un data frame será representada como un vector. Ej.: `vector1 <- c(1, 5, 3, -10)`. Una manera fácil de crear un vector con una secuencia de números es utilizar el operador `:`.

**Testes lógicos**: Una operación lógica no es más que un test que retorna verdadero o falso. El verdadero en R será representado por el valor `TRUE` y el falso por el valor `FALSE`. Estos nombres en R son reservados, es decir, no puedes llamar a ningún objeto `TRUE` o `FALSE`. Ej.: para testar si un valor es igual a otro (operador `==`) - `1 == 1` `TRUE` o `1 == 2` `FALSE`. Algunos de los principales operadores lógicos son:

-   `x < y` (¿x menor que y?)
-   `x <= y` (¿x menor o igual a y?)
-   `x > y` (¿x mayor que y?)
-   `x >= y` (¿x mayor o igual a y?)
-   `x == y` (¿x igual a y?)
-   `x != y` (¿x diferente de y?)
-   `!x` (Negación de x)
-   `x | y` (¿x o y son verdaderos?)
-   `x & y` (¿x y y son verdaderos?)
-   `x %in% y` (¿x pertenece a y?)
-   `xor(x, y)` (¿x o y son verdaderos, pero no ambos?)

**Valores especiales**: `NA` - representa la ausencia de información, es decir, la información existe, pero nosotros (y R) no sabemos cuál es. El `NA` para R no es más que el valor faltante o omitido de la Estadística.

**Operador pipe**: La idea del operador `%>%` (pipe) es muy simple: usar el valor resultante de la expresión del lado izquierdo como primer argumento de la función del lado derecho. Se usa el pipe (`|>` o `%>%`) para enfatizar una secuencia de comandos o acciones en el chunk y para evitar agregar el nombre del data frame dentro de la función `ggplot`. El pipe debe tener siempre un espacio antes de él y, generalmente, debe ser seguido por una nueva línea. Después de la primera etapa, cada línea debe tener dos espacios, lo que facilita agregar otras etapas o reorganizar las ya existentes.

**Operador cifrón**: Usar el comando cifrón permite acceder a columnas por el nombre. El uso es básicamente el siguiente - `datos$cifra`, donde `datos` especifica el conjunto de datos y `cifra` la variable que deseas extraer. Por ejemplo, para extraer los datos de macacos usa: `macac$macacos`.

## Aprendizaje del día

Esta guía cubre los fundamentos básicos de R. Con práctica y exploración, te familiarizarás más con el lenguaje y sus capacidades. ¡Buena suerte en tu viaje de aprendizaje con R!
